# -*- coding: utf-8 -*-
"""2D-plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1InFu1590jBv9qN25E7L8cMN2_AKCpIXU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('RAIN MEAN DATA.csv')

Y = []
i=1
while(i<=19):
  Y.append(i)
  if len(Y)%240==0:
    i+=1

z = np.array(19 * list(range(1,241)))
Y = np.array(Y)

x = np.array(data['Time'])

from mpl_toolkits.mplot3d import Axes3D

import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(18,15))
ax = fig.add_subplot(111,projection='3d')
"""
i=4
ax.plot(Y[240*(i-1):(240*i)-1],,x[240*(i-1):(240*i)-1],c='r',label=str(i))
i=5
ax.plot(Y[240*(i-1):(240*i)-1],x[240*(i-1):(240*i)-1],c='r',label=str(i))
"""
for i in range(1,20):
    plt.plot(z[240*(i-1):(240*i)-1],Y[240*(i-1):(240*i)-1]/2, x[240*(i-1):(240*i)-1],   c='r',label=str(i))
ax.set_xlabel('x axis')
ax.set_ylabel('y axis')
ax.set_zlabel('z axis')
plt.show()
